name: SurvivalProjectHelper
version: 1.0
authors:
  - xLixon
  - yHighPing
main: de.xLixon.yHighPing.Main.Main
commands:
  shop:
    aliases:
      - buy
    description: Ein kleiner Shop
  resetworld:
    aliases:
      - rswd
    description: Resetet alle Welten